### PR TITLE
User-friendly insulation counter & Fixed Create insulation Diving Suit

### PR DESCRIPTION
**Pull request by Nerbzzz**
Made Create Netherite Diving Suit insulate cold as it's also used for diving in water, I also made insulation values exceeding 999 display an infinite symbol to prevent confusion for players.

### CODE REVIEW

**Comment by Nerbzzz** [comment]
Might try and add it so that Diving Suit insulation only activates when the player is in the water, as wearing the suit with air in it is an easy and cheesy way to prevent anything temperature related.

LMK how y'all feel about that, and if I should do it

**Comment by Nerbzzz** [comment]
Added `minecraft:netherite_boots` to Diving Suit insulation because many people (myself included) do not want to sink to the bottom and want to swim while still being able to breathe underwater, this allows that.

**Comment by MikulDev** [comment]
A value of 999 for insulation isn't quite infinite, and your temperature actually can increase by a couple points when you have the diving suit on if there's enough lava around you. Now that I think about it, maybe a better way would be to ditch insulation and use attribute modifiers, which can block heat entirely. 

I think cold insulation is good as well, but it should definitely only activate in water. I will also add something to prevent the player from getting wet, since that wouldn't make much sense. 

I merged the netherite boots part, but I think I'll do the rest of this in a different way. Thanks for the suggestion/work!

**Comment by Nerbzzz** [comment]
Ah, I never actually realized the water droplets was being "wet", always thought of it as sweat for some reason. I'll be fix it on wednesdays because of a busy schedule. (If you haven't fixed it yourself by then)

**Pull request closed without merging**
